name: 'Joke of the day - every day (LATEST VERSION)'
on:
  workflow_dispatch:
  schedule:
    # once 9am (UTC+9) every day
    - cron:  '0 0 * * *'  
  
jobs:
  print-joke-of-the-day:
    runs-on: ubuntu-latest

    steps:
      - uses: h2floh/action-get-joke-of-the-day@main