name: CI on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  CIandUpdateDist:
    name: 'Do CI and after push artifact to feature branch'
    runs-on: ubuntu-latest

    steps:
    - name: Continuous Integration
      uses: ./../.github/workflows/CI

    - name: Commit and push build result
      uses: EndBug/add-and-commit@v7
      with:
        add: 'dist/index.js'
        message: 'adding dist/index.js result from CI'
        push: true
        signoff: true